name: Create Pull Request All Platforms
on:
  repository_dispatch:
    types: [create-pull-request-multi]
jobs:
  createPullRequest:
    name: Testing on ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: Create report file
        if:  matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest'
        run: date +%s > report.txt
      - name: Create report file (windows)
        if:  matrix.platform == 'windows-latest'
        run: echo %DATE% %TIME% > report.txt
      - name: Create Pull Request
        id: cpr
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add report file
          author-email: peter-evans@users.noreply.github.com
          author-name: Peter Evans
          title: '[Example] Add report file'
          body: |
            New report
            - Contains *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: report, automated pr
          assignees: peter-evans
          reviewers: peter-evans
          milestone: 1
          branch: example-patches
          branch-suffix: random
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
